name: self
on: push
jobs:
  self:
    runs-on: ubuntu-latest
    steps:
      - name: check
        uses: actions/checkout@v2
      - name: install
        run: make install
      - name: lint
        run: make lint
      - name: test
        run: make test
      - name: test-coverage
        run: make test-coverage
