name: self
on: push
jobs:
  self:
    runs-on: ubuntu-latest
    steps:
      - name: check
        uses: actions/checkout@v2
      - name: install
        run: make install
      - name: lint
        run: make lint
      - name: test
        run: make test
      - name: test-coverage
        # Publish code coverage on Code Climate
        # https://github.com/paambaati/codeclimate-action
        uses: paambaati/codeclimate-action@v2.7.4
        # Add Code Climate secret key
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true